package com.example.map.domain;

public class Community {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.cen_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String cenLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.cen_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String cenLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.name
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.door_num
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private Integer doorNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.households
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private Integer households;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.population
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private Integer population;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.house_num
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private Integer houseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.year
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.top_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String topLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.top_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String topLng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.bottom_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String bottomLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.bottom_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    private String bottomLng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.cen_lat
     *
     * @return the value of community.cen_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getCenLat() {
        return cenLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.cen_lat
     *
     * @param cenLat the value for community.cen_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setCenLat(String cenLat) {
        this.cenLat = cenLat == null ? null : cenLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.cen_lng
     *
     * @return the value of community.cen_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getCenLng() {
        return cenLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.cen_lng
     *
     * @param cenLng the value for community.cen_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setCenLng(String cenLng) {
        this.cenLng = cenLng == null ? null : cenLng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.name
     *
     * @return the value of community.name
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.name
     *
     * @param name the value for community.name
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.door_num
     *
     * @return the value of community.door_num
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public Integer getDoorNum() {
        return doorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.door_num
     *
     * @param doorNum the value for community.door_num
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setDoorNum(Integer doorNum) {
        this.doorNum = doorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.households
     *
     * @return the value of community.households
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public Integer getHouseholds() {
        return households;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.households
     *
     * @param households the value for community.households
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setHouseholds(Integer households) {
        this.households = households;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.population
     *
     * @return the value of community.population
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.population
     *
     * @param population the value for community.population
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.house_num
     *
     * @return the value of community.house_num
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public Integer getHouseNum() {
        return houseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.house_num
     *
     * @param houseNum the value for community.house_num
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setHouseNum(Integer houseNum) {
        this.houseNum = houseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.year
     *
     * @return the value of community.year
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.year
     *
     * @param year the value for community.year
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.top_lat
     *
     * @return the value of community.top_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getTopLat() {
        return topLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.top_lat
     *
     * @param topLat the value for community.top_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setTopLat(String topLat) {
        this.topLat = topLat == null ? null : topLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.top_lng
     *
     * @return the value of community.top_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getTopLng() {
        return topLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.top_lng
     *
     * @param topLng the value for community.top_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setTopLng(String topLng) {
        this.topLng = topLng == null ? null : topLng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.bottom_lat
     *
     * @return the value of community.bottom_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getBottomLat() {
        return bottomLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.bottom_lat
     *
     * @param bottomLat the value for community.bottom_lat
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setBottomLat(String bottomLat) {
        this.bottomLat = bottomLat == null ? null : bottomLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.bottom_lng
     *
     * @return the value of community.bottom_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public String getBottomLng() {
        return bottomLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.bottom_lng
     *
     * @param bottomLng the value for community.bottom_lng
     *
     * @mbg.generated Tue Nov 05 16:55:16 CST 2019
     */
    public void setBottomLng(String bottomLng) {
        this.bottomLng = bottomLng == null ? null : bottomLng.trim();
    }

    @Override
    public String toString() {
        return "Community{" +
                "cenLat='" + cenLat + '\'' +
                ", cenLng='" + cenLng + '\'' +
                ", name='" + name + '\'' +
                ", doorNum=" + doorNum +
                ", households=" + households +
                ", population=" + population +
                ", houseNum=" + houseNum +
                ", year='" + year + '\'' +
                ", topLat='" + topLat + '\'' +
                ", topLng='" + topLng + '\'' +
                ", bottomLat='" + bottomLat + '\'' +
                ", bottomLng='" + bottomLng + '\'' +
                '}';
    }
}